AllCops:
  TargetRubyVersion: 2.3

# Use Shopify Ruby style
inherit_from:
  - https://shopify.github.io/ruby-style-guide/rubocop.yml

Style/FrozenStringLiteralComment:
  Exclude:
    - '*.gemspec'
    - 'Gemfile'
    - 'Rakefile'
